### ISSUE TITLE
Ipad/Iphone en.strings not working

### ISSUE THREAD

**Issue by guerson** [BlinkID/blinkid-phonegap#10]
https://github.com/blinkinput/blinkinput-ios/blob/master/Samples/BlinkOCR-sample/BlinkOCR-sample/Base.lproj/en.strings

The Strings are not working on IOS.
It suppose to be a button with "cancel" and "Light" label. 
But, instead it showing this:
![strings](https://cloud.githubusercontent.com/assets/16294211/21367515/6677d76a-c6cc-11e6-8cba-a89cb78c72bf.png)

**Comment by guerson** [comment]
Can someone answering me please?

**Comment by Cerovec** [comment]
Hi Guerson,

we tried running a sample app generated using initCordovaDemoApp.sh script, and the result is the following.

Which language do you use?
How did you perform the integration?

Missing strings usually means that Microblink.bundle resource is not packaged in the resulting .ipa file for the app. Please make sure that it does.

![img_6703](https://cloud.githubusercontent.com/assets/628039/21775802/d157c7b8-d697-11e6-9d53-2993cee58eb2.PNG)

**Comment by jcular** [comment]
This is due to language on your device, internally our SDK uses .strings files located in .bundle for UI text which uses .strings files based on your device language. You can override this by setting language to "en", then it will use only english .strings files, or add other languages by adding .strings files with proper translation for that language.

Kind regards,
Jure
