### ISSUE TITLE
Adding custom Template to Phonegap plugin

### ISSUE THREAD

**Issue by ffranz84** [BlinkID/blinkid-phonegap#12]
Hello,

I want to implement a custom Template for a not yet supported card. I already found the templating example with the croatian ID card. My question now is: how do I get the new template into my phonegap plugin. I am not very firm in Java or Android so any hint will be apprechiated.
I already tried to import com.microblink.util into BlinkIdScanner.java, but the compiler only said "symbl not found". I am sure, I am making something fundametally wrong here and I need some help to get this to work.

**Comment by DoDoENT** [comment]
Hi @ffranz84,

unfortunately, Templating API is not exposed to PhoneGap, due to its complexity. You can implement the support for your card using native Java/Objective C API and then modify the PhoneGap plugin source to use your native integration to start scanning.

Another approach would be to create a full-blown javascript wrapper for entire Templating API, but this is complex and a lot of work.

**Comment by ffranz84** [comment]
Thank you  @DoDoENT, for your reply.
But I am kind of lost here. Do I have to adapt the teplate from the example and place it in the BlinkIdScanner.java of the plugin?

**Comment by DoDoENT** [comment]
Yes - you've got it right.

**Comment by ffranz84** [comment]
I will give it a try, prepare to hear from me again. Thank you!

**Comment by jcular** [comment]
Closed due to inactivity.
