### ISSUE TITLE
IBM MobileFirst Integrate - Android 

### ISSUE THREAD

**Issue by jagan27101986** [BlinkID/blinkid-phonegap#36]
I am currently working on a hybrid application and my cordova version is 3.7.0 where i am using IBM MobileFirst 7.1 version. There is no gradle file to compile as it comes as a part of Eclipse Plugin. I would like to know how i can integrate the phonegap plugin with my application without gradle. 

The query that i have is do we need Android SDK 24 which is 7.0 to run this application. ?

**Comment by DoDoENT** [comment]
In that case, you will need to perform [native eclipse integration](https://github.com/BlinkID/blinkid-android#eclipseIntegration) and then use the plugin source as a base for creating your own wrapper around your native SDK integration.

**Comment by jagan27101986** [comment]
Add appcompat-v7 library to your workspace and reference it by target project (modern ADT plugin for Eclipse does this automatically for all new android projects).

Is Android SDK 24 required  to run in Android or Android 6.0 will do ?

**Comment by DoDoENT** [comment]
Our SDK has been compiled using the latest Android SDK and you [should do that too](https://medium.com/google-developers/picking-your-compilesdkversion-minsdkversion-targetsdkversion-a098a0341ebd). You can always target older android version even if using the latest SDK.

**Comment by jagan27101986** [comment]
I created the Android Library Project with the instructions provided . the issue i am facing is after adding the project as library , i am getting an error as The container 'Android Dependencies' references non existing library 'bin\jar folder. Please advise as what needs to be done. Also i downloaded the Android 24 Version from SDK manager .

Also i didn't understand where about Adding appcompat-v7 library to your workspace and reference it by target project (modern ADT plugin for Eclipse does this automatically for all new android projects).

Could you please help me out with the same ?

**Comment by jagan27101986** [comment]
What should be the target build project API - 23 or 24 or more . Please advise the same. Also where can i get the appcompat-v7  library and also do we need to build path for the same in both the library project and main project ?

**Comment by jagan27101986** [comment]
Hi I am able to build APK based on the comments that you have provided. However when i call ; i see that no camera is getting opened or i am getting any error message in the application . Could you please advise on the same ?

**Comment by jagan27101986** [comment]
I am using Android SDK 6.0 with 23 as the API and also Cordova version 3.7.0 and also the ADT automatically created the android.support.v7.appcompat library when i created a new Android Project .. Is there anything i am missing for the camera to be inititated ?

**Comment by DoDoENT** [comment]
Which activity are you using? Are there any errors in ADB log?

**Comment by jagan27101986** [comment]
I didnt get about the Activity , Could you please explain in detail ? I am new to Eclipse Android. I can explain the stepls that i have done

**Comment by jagan27101986** [comment]
What is see is that ScanCard Class is not opening to the camera and no errors as i was printing step by step.

**Comment by jagan27101986** [comment]
I created a blank activity for the Library Project. Is it correct ?

**Comment by jagan27101986** [comment]
Could you please check and update on the query i have raised.

**Comment by jagan27101986** [comment]
Also to note that i am using JDK 1.6 and JRE 1.6 for building the Mobile Application . Is this also the reason for not identifying the Scanner ?

**Comment by DoDoENT** [comment]
After providing Scan Activity in your manifest, you should be able to use it from your test application written in Java, by following [native android integration instructions](https://github.com/BlinkID/blinkid-android#-performing-your-first-scan). However, to use that activity from your Cordova app, you will have to create your own Cordova plugin that will wrap the native integration code. You can use [our official open source plugin source code](https://github.com/BlinkID/blinkid-phonegap/tree/master/BlinkID/src/android) as basis for doing that, however you will need to adapt cordova-specific part of the source code to match the version you have.

This is not something that can be done quickly and easily. I suggest using more modern version of Cordova which allows you to use gradle-based build. As I see, IBM MobileFirst v8.0.0 supports [cordova-android v5.1.1](https://www.ibm.com/support/knowledgecenter/en/SSHS8R_8.0.0/com.ibm.worklight.dev.doc/dev/r_cordova_plugins.html) which uses [Android studio](https://mobilefirstplatform.ibmcloud.com/tutorials/en/foundation/8.0/installation-configuration/development/android/) for development of Android parts. However, you will need to use plugin from [this branch](https://github.com/BlinkID/blinkid-phonegap/tree/support/old-android-plugin/BlinkID/src/android) in order to work with cordova-android 5.1.1, as v5.1.1 is also outdated by today's standards (latest version is v7.0.0).

I really suggest that you upgrade to IBM MobileFirst v8.0 because this will at least give you possibility to use modern development tools for your app development. Eclipse support has been deprecated by more than 3 years ago and you will not find a lot of materials online that will help you with app development while using Eclipse.

**Comment by jagan27101986** [comment]
Thanks for the comments.  I will surely look into it.

**Comment by jagan27101986** [comment]
Is there a way whether the BLINK SDK can support Java JDK , JRE 1.6 and Cordova 3.7.0 with IBM MobileFirst ?

**Comment by DoDoENT** [comment]
BlinkID Phonegap plugin never had a support for such an old version of Cordova. However, early versions of [PDF417.mobi phonegap](https://github.com/PDF417/pdf417-phonegap) did have support for cordova < v4.0.0. You can [see how you should organise your code](https://github.com/PDF417/pdf417-phonegap/blob/v1.0.0/Pdf417/plugin.xml) in order to work with cordova v3.0.0, however I really do not recommend this - it is complicated and error-prone (all resources, assets, JARs and native libraries need to be manually managed from cordova plugin.xml description). We do not plan to officially support such old versions of Cordova.

**Comment by jcular** [comment]
Closed due to inactivity.
